### ISSUE TITLE
WL_DATA_DEVICE_MANAGER_* undeclared

### ISSUE THREAD

**Issue by zskdan** [mchalupa/wldbg#51]
I'm trying to build wldbg on an ubuntu 14.04 but it failed:

> $ make
> make  all-recursive
> make[1]: Entering directory `/build/zakaria/wayland/tools/wldbg'
> Making all in src
> make[2]: Entering directory`/build/zakaria/wayland/tools/wldbg/src'
>   CC       print.lo
> print.c: In function 'print_actions':
> print.c:389:13: error: 'WL_DATA_DEVICE_MANAGER_DND_ACTION_NONE' undeclared (first use in this function)
>   if (act == WL_DATA_DEVICE_MANAGER_DND_ACTION_NONE) {
>              ^
> print.c:389:13: note: each undeclared identifier is reported only once for each function it appears in
> print.c:395:12: error: 'WL_DATA_DEVICE_MANAGER_DND_ACTION_COPY' undeclared (first use in this function)
>   if (act & WL_DATA_DEVICE_MANAGER_DND_ACTION_COPY) {
>             ^
> print.c:400:12: error: 'WL_DATA_DEVICE_MANAGER_DND_ACTION_MOVE' undeclared (first use in this function)
>   if (act & WL_DATA_DEVICE_MANAGER_DND_ACTION_MOVE) {
>             ^
> print.c:405:12: error: 'WL_DATA_DEVICE_MANAGER_DND_ACTION_ASK' undeclared (first use in this function)
>   if (act & WL_DATA_DEVICE_MANAGER_DND_ACTION_ASK) {
>             ^
> make[2]: **\* [print.lo] Error 1
> make[2]: Leaving directory `/build/zakaria/wayland/tools/wldbg/src'
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory`build/zakaria/wayland/tools/wldbg'
> make: **\* [all] Error 2

**Comment by mchalupa** [comment]
Hi,

thanks for the report. This is a problem with wayland version. For a quick workaround you can revert the commit 7fd87ae2c1 . I'll try to fix it ASAP

**Comment by zskdan** [comment]
Thanks @mchalupa , it works perfectly after revert and fixing the minor issue below:

> objinfo/xdg-objinfo.c:149:4: error: ‘for’ loop initial declarations are only allowed in C99 mode
>     for (uint8_t idx = 0; idx < 10; ++idx) {
>     ^
