### ISSUE TITLE
assertion failed on EGL applications

### ISSUE THREAD

**Issue by zskdan** [mchalupa/wldbg#52]
wldbg failed to start when launching with an EGL Wayland application "weston-simple-egl",
but it works fine for shm ones.

> $ wldbg example -- weston-simple-egl
> ...
> ...
> weston-simple-egl: /project/build/bazoka/tmp/work/corei7-64-poky-linux/weston/1.8.0-r0/weston-1.8.0/clients/simple-egl.c:399: create_surface: Assertion `0' failed.
>  -- Destroying example pass

**Comment by mchalupa** [comment]
Thanks for the report,

this is a bug in weston-simple-egl, see https://patchwork.freedesktop.org/patch/76825/
